name: LightningRods 2
main: ca.kanoa.RodsTwo.RodsTwo
version: 1.0
author: 12323op
softdepend: [Vault]
description: The second edition of the LightningRods plugin.

permissions:
    lr.spawn:
        description: Allows use of the spawn commands.
        default: op
    lr.reload:
        description: Allows use of the reload command.
        default: op
    lr.overwrite:
        description: Allows use of the overwrite command.
        default: op
    lr.list:
        description: Allows use of /lr list.
        default: true
    lr.use.all:
        description: Allows use of all rods.
        default: op
    lr.craft.all:
        description: Allows crafting of all rods.
        default: op
    lr.cooldown.exempt:
        description: Turns of cooldowns.
        default: false
    lr.slowdownmessage:
        description: View the slowdown message
        default: true
        
commands:
    lightningrod:
        description:
        usage: /lightningrod <list/spawn/reload/overwrite>
        aliases: [lr, lrod]